apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - flux.yaml
  - cloudflared-deployment.yaml
  - ingress.yaml
  - landing.yaml
  - mongo.yaml
  - mongo-backup.yaml
  - arc
